apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.1.170:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: default
    user: oidc-token
  name: kubernetes
current-context: kubernetes
kind: Config
users:
- name: oidc-token
  user:
    token: TEST_TOKEN
