apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    # certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUTVJVmRad0NpWUF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1ESXdOREkyTlRaYUZ3MHpOVEV5TXpFd05ETXhOVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURCcUp6UmVYT00vRUVpenFSTE55NmdJUERZSVRvVk9QOUlydDBCdHpBMlVJWjB2eWpXZWU4bW9BZVkKUThoeWRtWUVUNW9adTV3Q3pYRzNQMGRuV2RLazBXMFZhOUhabWRDbnlZOWlDNFpDM0dSMFNvNTBRaUVSS1NQSApsNkoxRTNXcVpwanY0UnlOQkRxTzhmQ3NvbW9JcGJFalZPTVgwYUF4eGZSbFhpa1ZaRi9NRlpUMDd0dVJJSk8xCk9kdWkvWXVheWx3UU9ZNDFZMkI5RWRlQ0FYSTJLY2I1aW55dUx6RWlpUngyZWFoS3BPckZzNUZCMDRNRTVWa2UKbjhINGRDVXhrUlM4SWt1eDZ6ZFdXNEZhVlhzdUhlRzF6N01rUnpLdmVCNUNoTTlSaVRTMXBvcVlSdnVFaUpBQwo0M2RuWFFoVCt6Q2h4WGtoR0pDdlV0Yi9mdVNYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSZmMxVi9iTnU2c0lmQkN0NUs1ZVRzbVp3M1pqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmd0dXcxaUVYaApOQm9aTHBhUFpJVXFubS9jRWdXSFdKdmdPME9COVR6LzhuYVJoWTljLzBqNUdCS0dYNXhKZmg3V0lZVk55TUZuCnd4KzJLNUU2ZDRIWk8rQytBY0h6WDFpTGpjc2dqdlVUTjlQZEdsMVBPellLcHd6d05QT3BxWXkvd2N1TzdtMEEKeU5NSnN6S1BHQUlQT0JzU3M1WjhKb2Y4Nm94WThkNGJXTzdKVmZZWFZ2Wk5DZmY3TG9LMHNWelFHSmh2bThHRApaYWl3QVgyOEZ6bTdlYUg1aUZsSEkzRVdvMkdwT1BkdWlTRVV0L0V1MXBQQTNCSEJ4R1MyQlVUYUhSazF5b0dUCjhmcTNadmNmWlRTUWludC9TbGZwT0xFdEw4QnZtTHZRUTI0RnhBMGExdll5bEk3UzF6bjJ2TjdJaHEvRURTT2kKdXc5WDkyM2JJMFZGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.1.170:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: kube-system
    user: oidc
  name: kubernetes
current-context: kubernetes
kind: Config
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://gitlab.thegriffinshome.com
      - --oidc-client-id=7559b45c6c13286513b01df340c1e61479de9f0a84aa9e98e311bca865cf6d27
      command: kubectl
      env: null
      interactiveMode: Never
      provideClusterInfo: false
