apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-credentials
spec:
  refreshPolicy: Periodic
  refreshInterval: 60s  
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: pihole-credentials
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
      remoteRef:
        key: homelab/data/pihole-credentials
        property: password

