apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-manifests
  namespace: flux-system
spec:
  interval: 5m
  url: https://gitlab.thegriffinshome.com/homelab/platform-manifests
  ref:
    branch: main
  secretRef:
    name: fluxcd-gitlab-token
